events {}

http {
    # Docker internal DNS resolver (VERY IMPORTANT for Swarm)
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        # Internet Banking
        location /internet/ {
            proxy_pass http://internetbanking/;
        }

        # Mobile Banking
        location /mobile/ {
            proxy_pass http://mobilebanking/;
        }

        # Insurance
        location /insurance/ {
            proxy_pass http://insurance/;
        }

        # Loan
        location /loan/ {
            proxy_pass http://loan/;
        }
    }
}
